# Generated by Django 5.0.2 on 2025-03-21 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_notifications', models.BooleanField(default=True, verbose_name='복습 알림')),
                ('achievement_notifications', models.BooleanField(default=True, verbose_name='성취 알림')),
                ('reminder_notifications', models.BooleanField(default=True, verbose_name='학습 독려 알림')),
                ('notification_time', models.TimeField(default=django.utils.timezone.now, verbose_name='알림 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
            },
        ),
    ]
