# Generated by Django 5.0.2 on 2025-03-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_usernotificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogress',
            name='study_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='study.studysession'),
        ),
    ]
